#!/usr/bin/python3

"""
Converts a CSV file generated by Emotiv Pro
to a more standard CSV format

This script generates two files
1. <filename>_corrected.csv
	 A standard header -> column CSV file
2. <filename>_metadata.txt
	 The metadata contained in the header of the 
	 Emotiv Pro CSV file gets saved here

Each file can be fed into the lg_json_builder.py 
utility to generate an EEG Workbench compliant
JSON file
"""

import csv
import sys
import pandas as pd

if len(sys.argv) != 2:
    sys.exit(1)

filename = sys.argv[1]

metadata = []
headers = []

emotiv_pro_data = dict()
with open(filename, 'r') as csvfile:
    reader = csv.reader(csvfile)

    # cut out the first row and extract the metadata
    # save the proper csv headers
    metadata_stripped = False
    for row in reader:

        # extract the header row and process it
        if not metadata_stripped:
            metadata = row
            headers = metadata[5].split()
            metadata.pop(5)
            headers[0] = headers[0].replace('labels:', '')
            for header in headers:
                emotiv_pro_data[header] = []
            metadata_stripped = True
        # align each data point under it's proper column
        else:
            for i in range(len(headers)):
                emotiv_pro_data[headers[i]].append(row[i])

# print the corrected csv
dataframe = pd.DataFrame(emotiv_pro_data)
dataframe.to_csv(filename.split('.csv')[0] + "_corrected.csv")

# print the metadata to a file
with open(filename.split('.csv')[0] + "_metadata.txt", 'w') as f:
    for data in metadata:
        data = data.strip()
        f.write(data + '\n')

